// Common extended scalar types

module.exports = {
	ObjectID: "ObjectID",
  Date: "Date",
  Time: "Time",
  DateTime: "DateTime",
  UtcOffset: "UtcOffset",
  NonPositiveInt: "NonPositiveInt",
  PositiveInt: "PositiveInt",
  NonNegativeInt: "NonNegativeInt",
  NegativeInt: "NegativeInt",
  NonPositiveFloat: "NonPositiveFloat",
  PositiveFloat: "PositiveFloat",
  NonNegativeFloat: "NonNegativeFloat",
  NegativeFloat: "NegativeFloat",
  UnsignedFloat: "UnsignedFloat",
  UnsignedInt: "UnsignedInt",
  BigInt: "BigInt",
  Long: "Long",
  EmailAddress: "EmailAddress",
  URL: "URL",
  PhoneNumber: "PhoneNumber",
  PostalCode: "PostalCode",
  GUID: "GUID",
  HexColorCode: "HexColorCode",
  HSL: "HSL",
  HSLA: "HSLA",
  RGB: "RGB",
  RGBA: "RGBA",
  IPv4: "IPv4",
  IPv6: "IPv6",
  MAC: "MAC",
  Port: "Port",
  ISBN: "ISBN",
  USCurrency: "USCurrency",
  Currency: "Currency",
  JSON: "JSON",
  JSONObject: "JSONObject",
  Byte: "Byte", 
  Point: "Point",
  Linestring: "LineString",
  Polygon: "Polygon"
}